apiVersion: apps/v1
kind: Deployment
metadata:
  name: edu-msa-ui
  namespace: apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: edu-msa-ui
  template:
    metadata:
      labels:
        app: edu-msa-ui
    spec:
      containers:
      - name: edu-msa-ui
        image: seunghyejeong/project_cicd:2.0
        ports:
        - containerPort: 8080
